@Products_HostAddress = http://localhost:5008

GET {{Products_HostAddress}}/products/
Accept: application/json


###
GET {{Products_HostAddress}}/products/ce30e164-dde2-44e9-b639-4a8c4c6176c0
Accept: application/json


###
DELETE {{Products_HostAddress}}/products/{id}
Accept: application/json


###
POST {{Products_HostAddress}}/products
Accept: application/json
Content-Type: application/json

{
    "id": "ce30e164-dde2-44e9-b639-4a8c4c6176c0",
    "name": "",
    "cost": 100 , 
    "in_stock": 0 ,
    "description": ""
}

###
PUT {{Products_HostAddress}}/products/{id}
Accept: application/json

{
    "id": "ce30e164-dde2-44e9-b639-4a8c4c6176c0",
    "name": "",
    "cost": 0 , 
    "in_stock": 0 ,
    "description": ""
}

###
GET {{Products_HostAddress}}/products/ce30e164-dde2-44e9-b639-4a8c4c6176c0/negotiations
Accept: application/json


###
GET {{Products_HostAddress}}/products/ce30e164-dde2-44e9-b639-4a8c4c6176c0/negotiations/de30e164-dde2-44e9-b639-4a8c4c6176c0
Accept: application/json


###
POST {{Products_HostAddress}}/products/ce30e164-dde2-44e9-b639-4a8c4c6176c0/negotiations
Accept: application/json
Content-Type: application/json

{
    "id": "de30e164-dde2-44e9-b639-4a8c4c6176c0",
    "productId": "ce30e164-dde2-44e9-b639-4a8c4c6176c0", 
    "customerId": "fe30e164-dde2-44e9-b639-4a8c4c6176c0" ,
    "newCost": 30
}

###
PUT {{Products_HostAddress}}/products/ce30e164-dde2-44e9-b639-4a8c4c6176c0/negotiations/de30e164-dde2-44e9-b639-4a8c4c6176c0
Accept: application/json
Content-Type: application/json

{
    "id": "de30e164-dde2-44e9-b639-4a8c4c6176c0",
    "productId": "ce30e164-dde2-44e9-b639-4a8c4c6176c0",
    "status": "Rejected" , 
    "customerId": "fe30e164-dde2-44e9-b639-4a8c4c6176c0" ,
    "newCost": 30
}

###

